/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.3.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Cell { 'value' : Value, 'name' : string }
export interface ContactMessage {
  'id' : Id,
  'subject' : string,
  'name' : string,
  'createdAt' : Timestamp,
  'email' : string,
  'message' : string,
  'phone' : string,
}
export type Error = { 'FrontendOriginsNotConfigured' : null } |
  {
    'MixedSsoSources' : {
      'otherKeys' : Array<string>,
      'ssoKeys' : Array<string>,
    }
  } |
  { 'Stale' : { 'ageNs' : bigint } } |
  { 'MalformedCandid' : null } |
  { 'AmbiguousAttribute' : { 'field' : string, 'sources' : Array<string> } } |
  { 'NoAttributes' : null } |
  { 'UnknownNonce' : null } |
  { 'UntrustedSsoSource' : { 'domain' : string } } |
  { 'MissingField' : string } |
  { 'FrontendOriginMismatch' : { 'got' : string, 'expected' : Array<string> } };
export type Id = bigint;
export interface Product {
  'id' : Id,
  'motif' : string,
  'featured' : boolean,
  'name' : string,
  'createdAt' : Timestamp,
  'size' : string,
  'slug' : string,
  'description' : string,
  'category' : string,
  'price' : bigint,
  'material' : string,
  'images' : Array<string>,
}
export interface ProductFilter {
  'sort' : [] | [ProductSort],
  'search' : [] | [string],
  'category' : [] | [string],
}
export type ProductSort = { 'priceLowToHigh' : null } |
  { 'newest' : null } |
  { 'priceHighToLow' : null };
export interface Result { 'hasMore' : boolean, 'rows' : Array<Array<Cell>> }
export type Result__1 = { 'ok' : null } |
  { 'err' : Error };
export type Timestamp = bigint;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type Value = { 'int' : bigint } |
  { 'nat' : bigint } |
  { 'float' : number } |
  { 'bool' : boolean } |
  { 'null' : null } |
  { 'text' : string };
export interface _SERVICE {
  '_initialize_access_control' : ActorMethod<[], undefined>,
  '_internet_identity_sign_in_finish' : ActorMethod<[], Result__1>,
  '_internet_identity_sign_in_start' : ActorMethod<[], Uint8Array>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'execute' : ActorMethod<[string], Result>,
  /**
   * / Returns the backend API documentation as Markdown.
   */
  'getApiDoc' : ActorMethod<[], string>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  /**
   * / Returns a product by id, or null when it does not exist.
   */
  'getProduct' : ActorMethod<[Id], [] | [Product]>,
  /**
   * / Returns a product by slug, or null when it does not exist.
   */
  'getProductBySlug' : ActorMethod<[string], [] | [Product]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  /**
   * / Returns the distinct product categories.
   */
  'listCategories' : ActorMethod<[], Array<string>>,
  /**
   * / Returns the featured products.
   */
  'listFeaturedProducts' : ActorMethod<[], Array<Product>>,
  /**
   * / Lists products with optional category filter, name search, and sort order.
   */
  'listProducts' : ActorMethod<[ProductFilter], Array<Product>>,
  'schema' : ActorMethod<[], string>,
  /**
   * / Submits a contact message and returns the stored record.
   */
  'submitContactMessage' : ActorMethod<
    [string, string, string, string, string],
    ContactMessage
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];