/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.3.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Error = IDL.Variant({
  'FrontendOriginsNotConfigured' : IDL.Null,
  'MixedSsoSources' : IDL.Record({
    'otherKeys' : IDL.Vec(IDL.Text),
    'ssoKeys' : IDL.Vec(IDL.Text),
  }),
  'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
  'MalformedCandid' : IDL.Null,
  'AmbiguousAttribute' : IDL.Record({
    'field' : IDL.Text,
    'sources' : IDL.Vec(IDL.Text),
  }),
  'NoAttributes' : IDL.Null,
  'UnknownNonce' : IDL.Null,
  'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
  'MissingField' : IDL.Text,
  'FrontendOriginMismatch' : IDL.Record({
    'got' : IDL.Text,
    'expected' : IDL.Vec(IDL.Text),
  }),
});
export const Result__1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Value = IDL.Variant({
  'int' : IDL.Int,
  'nat' : IDL.Nat,
  'float' : IDL.Float64,
  'bool' : IDL.Bool,
  'null' : IDL.Null,
  'text' : IDL.Text,
});
export const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
export const Result = IDL.Record({
  'hasMore' : IDL.Bool,
  'rows' : IDL.Vec(IDL.Vec(Cell)),
});
export const Id = IDL.Nat;
export const Timestamp = IDL.Nat;
export const Product = IDL.Record({
  'id' : Id,
  'motif' : IDL.Text,
  'featured' : IDL.Bool,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'size' : IDL.Text,
  'slug' : IDL.Text,
  'description' : IDL.Text,
  'category' : IDL.Text,
  'price' : IDL.Nat,
  'material' : IDL.Text,
  'images' : IDL.Vec(IDL.Text),
});
export const ProductSort = IDL.Variant({
  'priceLowToHigh' : IDL.Null,
  'newest' : IDL.Null,
  'priceHighToLow' : IDL.Null,
});
export const ProductFilter = IDL.Record({
  'sort' : IDL.Opt(ProductSort),
  'search' : IDL.Opt(IDL.Text),
  'category' : IDL.Opt(IDL.Text),
});
export const ContactMessage = IDL.Record({
  'id' : Id,
  'subject' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'phone' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initialize_access_control' : IDL.Func([], [], []),
  '_internet_identity_sign_in_finish' : IDL.Func([], [Result__1], []),
  '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'execute' : IDL.Func([IDL.Text], [Result], ['query']),
  'getApiDoc' : IDL.Func([], [IDL.Text], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getProduct' : IDL.Func([Id], [IDL.Opt(Product)], ['query']),
  'getProductBySlug' : IDL.Func([IDL.Text], [IDL.Opt(Product)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listCategories' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'listFeaturedProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'listProducts' : IDL.Func([ProductFilter], [IDL.Vec(Product)], ['query']),
  'schema' : IDL.Func([], [IDL.Text], ['query']),
  'submitContactMessage' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [ContactMessage],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Error = IDL.Variant({
    'FrontendOriginsNotConfigured' : IDL.Null,
    'MixedSsoSources' : IDL.Record({
      'otherKeys' : IDL.Vec(IDL.Text),
      'ssoKeys' : IDL.Vec(IDL.Text),
    }),
    'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
    'MalformedCandid' : IDL.Null,
    'AmbiguousAttribute' : IDL.Record({
      'field' : IDL.Text,
      'sources' : IDL.Vec(IDL.Text),
    }),
    'NoAttributes' : IDL.Null,
    'UnknownNonce' : IDL.Null,
    'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
    'MissingField' : IDL.Text,
    'FrontendOriginMismatch' : IDL.Record({
      'got' : IDL.Text,
      'expected' : IDL.Vec(IDL.Text),
    }),
  });
  const Result__1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Value = IDL.Variant({
    'int' : IDL.Int,
    'nat' : IDL.Nat,
    'float' : IDL.Float64,
    'bool' : IDL.Bool,
    'null' : IDL.Null,
    'text' : IDL.Text,
  });
  const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
  const Result = IDL.Record({
    'hasMore' : IDL.Bool,
    'rows' : IDL.Vec(IDL.Vec(Cell)),
  });
  const Id = IDL.Nat;
  const Timestamp = IDL.Nat;
  const Product = IDL.Record({
    'id' : Id,
    'motif' : IDL.Text,
    'featured' : IDL.Bool,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'size' : IDL.Text,
    'slug' : IDL.Text,
    'description' : IDL.Text,
    'category' : IDL.Text,
    'price' : IDL.Nat,
    'material' : IDL.Text,
    'images' : IDL.Vec(IDL.Text),
  });
  const ProductSort = IDL.Variant({
    'priceLowToHigh' : IDL.Null,
    'newest' : IDL.Null,
    'priceHighToLow' : IDL.Null,
  });
  const ProductFilter = IDL.Record({
    'sort' : IDL.Opt(ProductSort),
    'search' : IDL.Opt(IDL.Text),
    'category' : IDL.Opt(IDL.Text),
  });
  const ContactMessage = IDL.Record({
    'id' : Id,
    'subject' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'phone' : IDL.Text,
  });
  
  return IDL.Service({
    '_initialize_access_control' : IDL.Func([], [], []),
    '_internet_identity_sign_in_finish' : IDL.Func([], [Result__1], []),
    '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'execute' : IDL.Func([IDL.Text], [Result], ['query']),
    'getApiDoc' : IDL.Func([], [IDL.Text], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getProduct' : IDL.Func([Id], [IDL.Opt(Product)], ['query']),
    'getProductBySlug' : IDL.Func([IDL.Text], [IDL.Opt(Product)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listCategories' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'listFeaturedProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'listProducts' : IDL.Func([ProductFilter], [IDL.Vec(Product)], ['query']),
    'schema' : IDL.Func([], [IDL.Text], ['query']),
    'submitContactMessage' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [ContactMessage],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };